#!/usr/bin/env bash
#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Script to bootstrap a linux box
#
# Authors:
#   Ben O'Hara <bohara@gmail.com>
#

if [[ "$OSTYPE" != "linux"* ]]; then
  echo "$0 : Will only run on Linux"
  exit 1
fi

DIR=$(cd $(dirname "$0"); pwd)

###############################################################################
# apt-get
###############################################################################

# if [[ -f $DIR/packages/apt ]]; then
#   exec<$DIR/packages/apt
#   while read line
#   do
#     if [[ ! "$line" =~ (^#|^$) ]]; then
#       packages="$packages $line"
#     fi
#   done
#   sudo apt-get -y install $packages
# fi

###############################################################################
# pacman
###############################################################################

# sudo pacman -Syu;

# if [[ -f $DIR/packages/apt ]]; then
#   exec<$DIR/packages/apt
#   while read line
#   do  
#     if [[ ! "$line" =~ (^#|^$) ]]; then
#       packages="$packages $line"
#     fi
#   done
#   sudo pamac install --no-confirm $packages
# fi


###############################################################################
# yay
###############################################################################

# Update core repositories (non-interactive)
sudo pacman -Syu --noconfirm

# Install yay (AUR helper) if not already installed
if ! command -v yay >/dev/null 2>&1; then
  sudo pacman -S --needed --noconfirm base-devel git
  tmpdir=$(mktemp -d)
  git clone https://aur.archlinux.org/yay.git "$tmpdir/yay"
  (cd "$tmpdir/yay" && makepkg -si --noconfirm)
  rm -rf "$tmpdir"
fi

if [[ -f "$DIR/packages/apt" ]]; then
  packages=""
  while IFS= read -r line; do
    [[ "$line" =~ (^#|^$) ]] && continue
    packages+=" $line"
  done < "$DIR/packages/apt"
  if [[ -n "$packages" ]]; then
    yay -S --noconfirm --needed $packages
  fi
fi

sh $DIR/oh-my-zsh.sh

# sudo update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60
# sudo update-alternatives --config vi
# sudo update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60
# sudo update-alternatives --config vim
# sudo update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
# sudo update-alternatives --config editor
