#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Executes commands at login post-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Ben O'Hara <bohara@gmail.com>
#

# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  # Honour oh-my-zsh's versioned dump ($ZSH_COMPDUMP); fall back to the default.
  dump_file="${ZSH_COMPDUMP:-$HOME/.zcompdump}"
  if [[ -s "$dump_file" && ( "$dump_file" -nt "${dump_file}.zwc" || ! -s "${dump_file}.zwc" ) ]]; then
    zcompile "$dump_file"
  fi

  # Set environment variables for launchd processes.
  if [[ "$OSTYPE" == darwin* ]]; then
    for env_var in PATH MANPATH; do
      launchctl setenv "$env_var" "${(P)env_var}" 2>/dev/null
    done
  fi
} &!

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
