#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Ben O'Hara <bohara@gmail.com>
#

# Customize to your needs...

export TERMINAL=kitty

eval "$(/opt/homebrew/bin/brew shellenv)"
# Add .NET Core SDK tools
export PATH="$PATH:/Users/chris/.dotnet/tools"
