# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=/home/chris/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
#ZSH_THEME="chriscanal"
ZSH_THEME=""
SPACESHIP_DOCKER_SYMBOL=""
SPACESHIP_BATTERY_SHOW=false 

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=$HOME/.dotfiles/zsh/custom

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git docker docker-compose npm zsh-syntax-highlighting nvm zsh-completions zsh-autosuggestions extract dotnet gitignore)

source $ZSH/oh-my-zsh.sh
eval "$(starship init zsh)"

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LC_ALL=en_GB.UTF-8
# export LC_COLLATE=C
# export LANG=en_GB.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

SPACESHIP_PROMPT_ADD_NEWLINE=false

export PATH=$PATH:/home/chris/.dotfiles/bin
export PATH=$PATH:$HOME/.docker/bin

export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock

autoload bashcompinit && bashcompinit

export DOTNET_ROOT="$HOME/.dotnet"
export PATH="$HOME/.dotnet:$PATH"

# Ensure SSH key permissions are correct before loading keychain
if [ -d "$HOME/.ssh/master" ]; then
  chmod 700 "$HOME/.ssh" "$HOME/.ssh/master" 2>/dev/null
  find "$HOME/.ssh/master" -type f -name '*.pub' -exec chmod 644 {} \;
  find "$HOME/.ssh/master" -type f ! -name '*.pub' -exec chmod 600 {} \;
fi

ssh_keys=()
for ssh_key in ~/.ssh/master/id_*(N); do
  [[ "$ssh_key" == *.pub ]] || ssh_keys+=("$ssh_key")
done
if (( ${#ssh_keys} )); then
  eval $(keychain --eval --quiet "${ssh_keys[@]}")
fi
unset ssh_key ssh_keys

# pnpm
export PNPM_HOME="/home/chris/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
export PATH="$HOME/.local/bin:$PATH"


# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

# Local secrets (gitignored; see zsh/secrets.local)
[ -f "$HOME/.dotfiles/zsh/secrets.local" ] && source "$HOME/.dotfiles/zsh/secrets.local"

alias claude-ocd='CLAUDE_CONFIG_DIR=~/.claude-ocd /home/chris/.local/bin/claude'
alias claude-abcs='CLAUDE_CONFIG_DIR=~/.claude-abcs /home/chris/.local/bin/claude'
alias claude="echo 'Use specific commands: claude-ocd or claude-abcs'"

# Reset terminal mouse tracking at each prompt. A program suspended with
# Ctrl+Z cannot emit its disable sequence, which otherwise makes kitty send
# wheel events to zsh history instead of scrolling its own scrollback.
autoload -Uz add-zsh-hook
__reset_mouse_tracking() { print -n '\e[?1000l\e[?1002l\e[?1003l\e[?1006l\e[?1015l' }
add-zsh-hook precmd __reset_mouse_tracking
